export const REGRAS_LEGADOS = {
  'to-ficando-bom': 'Escolha uma vez a partir do nível 5: aumente um atributo em 2, respeitando o limite de atributo da campanha. Não pode ser escolhido novamente.',
  esquiva: 'Receba +1 na Defesa e +1 em Reflexos. Não acumula com outro Legado que conceda bônus fixo às duas defesas.',
  'leitura-labial': 'Você compreende falas a até 30 m quando enxerga claramente a boca. Sob pressão ou visão parcial, faça Percepção contra DT 15; isso não atravessa máscaras ou idiomas desconhecidos.',
  'maos-leves': 'Sacar ou guardar um item simples vira ação livre uma vez por turno; trocar equipamento complexo continua usando Movimento.',
  'artista-marcial': 'A partir do nível 3, escolha proficiência com armas marciais ou armaduras marciais. Pode ser escolhido novamente no nível 7 para receber a outra proficiência.',
  'kit-diverso': 'Escolha um kit de ofício ou exploração. Ele ocupa um espaço adicional; ao concluir um descanso, você repõe componentes mundanos, mas não itens raros, mágicos ou com preço individual.',
  'nao-e-tao-pesado': 'Reduza em 1 a penalidade de uma armadura ou escudo escolhido. Pode ser adquirido duas vezes, uma para cada categoria.',
  correntes: 'Você pode arremessar uma arma corpo a corpo até a distância Curta e recuperá-la com sua ação de Movimento. Isso não concede ataque adicional nem ignora a proficiência da arma.',
  'bala-agil': 'Uma vez por turno, some o modificador de Destreza ao dano de um ataque à distância. O mesmo modificador não pode ser somado duas vezes ao mesmo dano.',
  'sempre-no-x1': 'Uma vez por turno, cause +2 de dano contra um alvo sem aliados adjacentes. Não exige teste extra de Furtividade.',
  'magico-interrogacao': 'Ao escolher o Legado, selecione conjuração ou resistência mágica. Uma vez por cena, role com vantagem no tipo escolhido.',
  'magico-exclamacao': 'Uma vez por cena, reduza em uma ação o tempo de concentração de uma magia, com mínimo de uma ação. Exige nível 7 e não afeta rituais.',
  'sem-chance': 'Uma vez por descanso, ao obter 1 natural, repita o d20 e mantenha o novo resultado. Isso não remove falhas críticas do jogo.',
  rapidinho: 'Aumente o movimento em 1,5 m. Pode ser escolhido uma segunda vez para mais 1,5 m.',
  'sou-bom-nisso': 'Escolha Luta ou Pontaria e receba +2. Não concede vantagem e não pode ser escolhido para as duas perícias.',
  cozinheiro: 'Durante um descanso, prepare alimento para até seis criaturas. Cada uma reduz 1 Cansaço e melhora sua recuperação em uma categoria, no máximo Boa. Uma criatura recebe esse benefício apenas uma vez por dia.',
  'mais-potente': 'Ao usar duas mãos em uma arma versátil, cause +2 de dano uma vez por turno, em vez de +4 no ataque.',
  'sempre-foi-assim': 'Uma vez por turno, uma arma originalmente de duas mãos causa um dado adicional; exige nível 7.',
  'ainda-nao': 'Uma vez por cena, receba vantagem no primeiro teste de Morrendo ou contra dano massivo. Exige nível 5.',
  desonroso: 'Uma vez por cena, receba vantagem em um ataque contra oponente desarmado. Remova o bônus de +4 para desviar de todos os ataques.',
  'codigo-de-etica': 'Contra oponente armado, receba +2 na iniciativa e cause +2 de dano uma vez por turno. Remova dano igual ao nível e iniciativa automática.',
  monstro: 'Uma vez por turno, some novamente o modificador de Força ao dano corpo a corpo. Não dobre o modificador em todos os ataques.',
  'ossos-duros': 'Redução 2 contra dano físico, aumentando para 3 no nível 15. Não acumula com outra redução fixa.',
  bruto: 'Enquanto não usar armadura, some metade do modificador de Força à Defesa, arredondado para baixo, limitado a +2.',
  flexivel: 'Uma vez por rodada, depois de usar sua reação, gaste 2 Mana para recuperar a reação. Exige nível 10.',
  'instinto-animal': 'Receba +3 na Iniciativa estática e não fique Surpreendido por ameaças percebidas. Não usa vantagem porque Iniciativa não é rolada.',
  'mao-pesada': 'Ao obter crítico corpo a corpo, empurre o alvo 3 m. Ele testa Fortitude contra sua DT para não cair; criaturas duas categorias maiores não são empurradas.',
  'quebra-dente': 'Após um crítico corpo a corpo, o próximo ataque contra o alvo recebe +2. Não reduz Defesa até o fim do combate nem acumula.',
  'sem-tempo-irmao': 'No início do combate, antes do primeiro turno, você pode se mover até metade do deslocamento. Não pode atacar, usar item ou ativar habilidade durante esse movimento.',
  'to-de-pe-ainda': 'Enquanto estiver com metade da Vida ou menos, receba +1 na Defesa e Redução 1 contra dano físico. Não acumula com outra redução fixa.',
  'veterano-de-guerra': 'Recupere 25% a mais de PV ou Mana em cada descanso, arredondado para cima, em vez de dobrar a recuperação.',
  'sortudo-pra-cacete': 'Uma vez por sessão, peça ao mestre para repetir uma rolagem de evento aleatório e aceite o segundo resultado.',
  'mentiroso-nato': 'Receba +2 em Enganação. Uma vez por cena, role um teste de Enganação com vantagem; mentiras simples dispensam teste apenas quando o alvo não possui motivo para desconfiar.',
  posturado: 'Receba +5 na Defesa passiva contra ser derrubado ou empurrado. Uma vez por cena, ao falhar nessa resistência, permaneça no lugar mesmo assim.',
  'ja-fui-clt': 'Uma vez por dia, reduza em 1 o Cansaço que acabaria de receber, no mínimo zero.',
  selvagem: 'Animais comuns começam neutros e não atacam sem ameaça ou provocação. Animais treinados, famintos ou sobrenaturais ainda podem exigir Adestramento contra a DT da cena.',
};

export const REQUISITOS_LEGADOS_V1 = {
  'to-ficando-bom': [{ nivel_personagem: 5 }],
  'artista-marcial': [{ nivel_personagem: 3 }],
  'magico-exclamacao': [{ nivel_personagem: 7 }],
  'sempre-foi-assim': [{ nivel_personagem: 7 }],
};
