export const TOPICOS = [
  {
    id: 'sistema-base',
    titulo: 'Sistema Base',
    simbolo: 'SB',
    icone: 'sistema-base.webp',
    accent: 'var(--gold)',
    resumo: 'Criação, atributos, Mana e as fórmulas fundamentais da ficha.',
  },
  {
    id: 'pericias',
    titulo: 'Perícias e Resistências',
    simbolo: 'PR',
    icone: 'pericias-resistencias.webp',
    accent: 'var(--frost)',
    resumo: 'Graus, DTs, vantagem e os quatro resultados possíveis de um teste.',
  },
  {
    id: 'acoes',
    titulo: 'Ações, Reações e Dano',
    simbolo: 'AR',
    icone: 'acoes-reacoes-dano.webp',
    accent: 'var(--blood)',
    resumo: 'O que fazer no turno, como reagir e como resolver ataques.',
  },
  {
    id: 'distancias',
    titulo: 'Distâncias',
    simbolo: 'DI',
    icone: 'distancias.webp',
    accent: 'var(--neon)',
    resumo: 'Faixas de alcance e conversão para mapas com quadrados de 1,5 metro.',
  },
  {
    id: 'ferimentos',
    titulo: 'Ferimentos e Morrendo',
    simbolo: 'FM',
    icone: 'ferimentos-criticos.webp',
    accent: 'var(--arkania)',
    resumo: 'Vida negativa, estabilização, morte e consequências de ferimentos graves.',
  },
  {
    id: 'coreografia',
    titulo: 'Coreografia de Combate',
    simbolo: 'CC',
    icone: 'coreografia-combate.webp',
    accent: 'var(--arkania-glow)',
    resumo: 'Ações cinematográficas com riscos escolhidos antes da rolagem.',
  },
  {
    id: 'descanso',
    titulo: 'Descanso e Cansaço',
    simbolo: 'DC',
    icone: 'descanso-cansaco.webp',
    accent: 'var(--star)',
    resumo: 'Recuperação de Vida e Mana, qualidade do abrigo e desgaste acumulado.',
  },
  {
    id: 'treinar',
    titulo: 'Treinamento',
    simbolo: 'TR',
    icone: 'treinar.webp',
    accent: 'var(--moss)',
    resumo: 'Tempo, requisitos e limites para avançar Graus de Perícia.',
  },
  {
    id: 'xp',
    titulo: 'Progressão e XP',
    simbolo: 'XP',
    icone: 'xp-niveis.webp',
    accent: 'var(--gold-light)',
    resumo: 'A tabela universal de personagem e de classe, do nível 1 ao 40.',
  },
  {
    id: 'magia-fluxo',
    titulo: 'Magia e Fluxo',
    simbolo: 'FL',
    icone: 'magia-fluxo.png',
    accent: 'var(--arkania)',
    status: 'desenvolvimento',
    resumo: 'Mana, conexão com Fluxo, círculos e conjuração.',
  },
  {
    id: 'condicoes',
    titulo: 'Condições Especiais',
    simbolo: 'CE',
    icone: 'condicoes-especiais.webp',
    accent: 'var(--arkania)',
    resumo: 'Sanidade, iniciativa, defesas passivas e estados críticos.',
  },
  {
    id: 'classes',
    titulo: 'Classes',
    simbolo: 'CL',
    icone: 'classe.webp',
    accent: 'var(--blood)',
    grupo: 'Personagens',
    catalogo: 'classes',
    resumo: 'Vida, Mana, progressão universal e regras de multiclasse.',
  },
  {
    id: 'classes-comuns',
    titulo: 'Classes Comuns',
    simbolo: 'CC',
    icone: 'classes-comuns.png',
    accent: 'var(--gold)',
    grupo: 'Personagens',
    hierarquia: 'subtopico',
    pai: 'classes',
    catalogo: 'classes',
    resumo: 'Classes disponíveis em todas as Árvores.',
  },
  {
    id: 'classes-especiais',
    titulo: 'Classes Especiais',
    simbolo: 'CE',
    icone: 'classes-especiais.png',
    accent: 'var(--arkania)',
    grupo: 'Personagens',
    hierarquia: 'subtopico',
    pai: 'classes',
    catalogo: 'classes',
    resumo: 'Uma classe geral e dez exclusivas de Árvore, adquiridas a partir do nível total 15.',
  },
  {
    id: 'racas',
    titulo: 'Raças',
    simbolo: 'RA',
    icone: 'raca.webp',
    accent: 'var(--moss)',
    grupo: 'Personagens',
    catalogo: 'racas',
    resumo: 'Recursos, fisiologias e características raciais.',
  },
  {
    id: 'racas-comuns',
    titulo: 'Raças Comuns',
    simbolo: 'RC',
    icone: 'racas-comuns.png',
    accent: 'var(--neon)',
    grupo: 'Personagens',
    hierarquia: 'subtopico',
    pai: 'racas',
    catalogo: 'racas',
    resumo: 'Povos encontrados em todas as Árvores.',
  },
  {
    id: 'racas-especiais',
    titulo: 'Raças Especiais',
    simbolo: 'RE',
    icone: 'racas-especiais.png',
    accent: 'var(--frost)',
    grupo: 'Personagens',
    hierarquia: 'subtopico',
    pai: 'racas',
    catalogo: 'racas',
    resumo: 'Recompensas ou transformações poderosas autorizadas pelo mestre.',
  },
  {
    id: 'legados-ascensao',
    titulo: 'Legados de Ascensão',
    simbolo: 'LA',
    icone: 'legados-de-ascensao.webp',
    accent: 'var(--gold-light)',
    grupo: 'Personagens',
    catalogo: 'legados',
    resumo: 'Aptidões recebidas a cada cinco níveis totais.',
  },
];

export function topicoPorId(id) {
  return TOPICOS.find(topico => topico.id === id) || null;
}
